name: Secure Code Review with Snowflake Cortex

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  cortex_review:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
      
    - name: Install dependencies
      run: |
        pip install snowflake-connector-python

    # - name: Extract PR diff
    #   id: diff
    #   run: |
    #     git fetch origin ${{ github.event.pull_request.base.ref }}
    #     git diff origin/${{ github.event.pull_request.base.ref }}...HEAD > diff.patch

    - name: Run Snowflake Cortex Review
      id: cortex_review
      run: |
        python scripts/code_review.py

    - name: Post Review Comment
      uses: peter-evans/create-or-update-comment@v4
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: ${{ steps.cortex_review.outputs.review }}
